# Generated by Django 5.2.6 on 2025-12-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('lease', 'Lease'), ('inheritance', 'Inheritance'), ('transfer', 'Transfer')], max_length=50)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='owners.ownerprofile')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_land_transactions', to='land.landparcel')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='owners.ownerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('tax', 'Tax'), ('fee', 'Fee'), ('penalty', 'Penalty')], max_length=50)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(default='paid', max_length=50)),
                ('parcel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_payments', to='land.landparcel')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.ownerprofile')),
            ],
        ),
    ]
