# Generated by Django 5.2.6 on 2025-12-09 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('parcel_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('land_use_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
                ('in_north', models.CharField(blank=True, max_length=255, null=True)),
                ('in_east', models.CharField(blank=True, max_length=255, null=True)),
                ('in_west', models.CharField(blank=True, max_length=255, null=True)),
                ('in_south', models.CharField(blank=True, max_length=255, null=True)),
                ('parcel_file', models.FileField(blank=True, null=True, upload_to='parcel_docs/')),
                ('cadastral_number', models.CharField(max_length=100, unique=True)),
                ('survey_number', models.CharField(blank=True, max_length=50, null=True)),
                ('block_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sector_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mouza_name', models.CharField(blank=True, max_length=100, null=True)),
                ('land_use_zone', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Agricultural', 'Agricultural'), ('Public', 'Public'), ('Mixed', 'Mixed')], max_length=50, null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title_deed_number', models.CharField(blank=True, max_length=100, null=True)),
                ('current_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('annual_tax_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('development_status', models.CharField(blank=True, choices=[('Undeveloped', 'Undeveloped'), ('Under_Construction', 'Under Construction'), ('Developed', 'Developed'), ('Government_Hold', 'Government Hold')], max_length=50, null=True)),
                ('has_structures', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
