# Generated by Django 5.2.6 on 2025-12-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='id_card_back',
            field=models.ImageField(blank=True, help_text='Back side of national ID card', null=True, upload_to='owner_ids/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='id_card_front',
            field=models.ImageField(blank=True, help_text='Front side of national ID card', null=True, upload_to='owner_ids/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture of the owner', null=True, upload_to='owner_profiles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text="Owner's signature", null=True, upload_to='owner_signatures/%Y/%m/%d/'),
        ),
    ]
