# Generated by Django 5.2.6 on 2025-12-10 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
        ('owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('Sole', 'Sole Ownership'), ('Joint', 'Joint Ownership'), ('Co-owner', 'Co-owner'), ('Leasehold', 'Leasehold'), ('Mortgage', 'Mortgage Holder'), ('Easement', 'Easement Holder'), ('Power_of_Attorney', 'Power of Attorney')], default='Sole', max_length=20)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('acquisition_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Inheritance', 'Inheritance'), ('Gift', 'Gift'), ('Government_Allocation', 'Government Allocation'), ('Auction', 'Auction'), ('Exchange', 'Exchange'), ('Court_Order', 'Court Order'), ('Partition', 'Partition')], default='Purchase', max_length=25)),
                ('acquisition_date', models.DateField()),
                ('acquisition_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deed_number', models.CharField(blank=True, max_length=100, null=True)),
                ('deed_date', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registrar_office', models.CharField(blank=True, max_length=200, null=True)),
                ('stamp_duty_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lease_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mortgage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mortgagee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_type', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Gift', 'Gift'), ('Inheritance', 'Inheritance'), ('Foreclosure', 'Foreclosure'), ('Surrender', 'Surrender')], max_length=20, null=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Under_Review', 'Under Review'), ('Disputed', 'Disputed')], default='Pending', max_length=20)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('is_current_owner', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_records', to='owners.ownerprofile')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_records', to='land.landparcel')),
                ('transfer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to_records', to='owners.ownerprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Title_Deed', 'Title Deed'), ('Survey_Map', 'Survey Map'), ('Tax_Receipt', 'Tax Receipt'), ('Identity_Proof', 'Identity Proof'), ('Address_Proof', 'Address Proof'), ('Sale_Deed', 'Sale Deed'), ('Gift_Deed', 'Gift Deed'), ('Mortgage_Deed', 'Mortgage Deed'), ('Partition_Deed', 'Partition Deed'), ('Court_Order', 'Court Order'), ('Death_Certificate', 'Death Certificate'), ('Succession_Certificate', 'Succession Certificate'), ('Building_Permit', 'Building Permit'), ('Encumbrance_Certificate', 'Encumbrance Certificate')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='land_documents/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('related_parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='land.landparcel')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('ownership_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.ownershiprecord')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ownershiprecord',
            index=models.Index(fields=['parcel', 'is_current_owner'], name='records_own_parcel__32d3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiprecord',
            index=models.Index(fields=['owner', 'is_current_owner'], name='records_own_owner_i_5a1d04_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiprecord',
            index=models.Index(fields=['acquisition_date'], name='records_own_acquisi_fc09b8_idx'),
        ),
    ]
